{{- range until (.Values.query_jobs | int) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: dydbtester-query- {{- . }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        action: query
        purpose: dydbtester
    spec:
      serviceAccountName: dynamodb
      restartPolicy: Never
      containers:
      - name: dynamodbtester
        image: {{ quote $.Values.image }}
        env:
        {{- range $key, $val := $.Values.env }}
          - name: {{ $key }}
            value: {{ quote $val }}
        {{- end }}
          - name: ACTION
            value: query
        resources:
          requests:
            memory: 1024M
            cpu: 250m
---
{{- end }}
{{- range until (.Values.batch_get_jobs | int) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: dydbtester-batch-get- {{- . }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        action: batch-get
        purpose: dydbtester
    spec:
      serviceAccountName: dynamodb
      restartPolicy: Never
      containers:
      - name: dynamodbtester
        image: {{ quote $.Values.image }}
        resources:
          requests:
            memory: 1024M
            cpu: 250m
        env:
        {{- range $key, $val := $.Values.env }}
          - name: {{ $key }}
            value: {{ quote $val }}
        {{- end }}
          - name: ACTION
            value: get
          - name: BATCH
            value: "true"
---
{{- end }}
{{- range until (.Values.get_jobs | int) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: dydbtester-get- {{- . }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        action: get
        purpose: dydbtester
    spec:
      serviceAccountName: dynamodb
      restartPolicy: Never
      containers:
      - name: dynamodbtester
        image: {{ quote $.Values.image }}
        resources:
          requests:
            memory: 1024M
            cpu: 250m
        env:
        {{- range $key, $val := $.Values.env }}
          - name: {{ $key }}
            value: {{ quote $val }}
        {{- end }}
          - name: ACTION
            value: get
---
{{- end }}
{{- range until (.Values.put_jobs | int ) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: dydbtester-put- {{- . }}
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        action: put
        purpose: dydbtester
    spec:
      serviceAccountName: dynamodb
      restartPolicy: Never
      containers:
      - name: dynamodbtester
        image: {{ quote $.Values.image }}
        env:
        {{- range $key, $val := $.Values.env }}
          - name: {{ $key }}
            value: {{ quote $val }}
        {{- end }}
          - name: ACTION
            value: put
{{- end }}