#batch_get_jobs: 1
#get_jobs: 1
query_jobs: 100
#put_jobs: 1
image: 074767584099.dkr.ecr.us-east-1.amazonaws.com/dynamodbtester:test
env:
  THREADS: 100
  MESSAGES: 100
  PRIMARYKEY: accountId
  SORTKEY: resourceId
  TABLE: pending_transaction_events
  AWS_REGION: us-east-1
  AWS_SDK_LOAD_CONFIG: true