#batch_get_jobs: 1
#get_jobs: 1
query_jobs: 100
#put_jobs: 1
image: public.ecr.aws/j6o4r1h6/dynamodbtester:test
env:
  THREADS: 100
  MESSAGES: 100
  PRIMARYKEY: accountId
  SORTKEY: resourceId
  TABLE: TestString
  AWS_REGION: us-east-1
  AWS_SDK_LOAD_CONFIG: true