batch_get_jobs: 10
query_jobs: 10
put_jobs: 1
image: public.ecr.aws/j6o4r1h6/dynamodbtester:latest
env:
  threads: 100
  messages: 10000
  primaryKey: AccountId
  sortKey: ResourceId
  table: Test
  Log: false
  AWS_REGION: us-east-1
  AWS_SDK_LOAD_CONFIG: true
