apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: dynamodbtester
        image: awalkerm/dynamodbtester
        env:
          - name: MESSAGES
            value: 10
          - name: THREADS
            value: 10
          - name: ACTION
            value: get
      